version: "3"

services:
  server:
    image: golang:bullseye
    working_dir: /go/src/app
    depends_on:
      - db
    volumes:
      - ..:/app
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  webdb:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: db
